### ISSUE TITLE
Jolokia always accessed via TLS on OpenShift 3.4

### ISSUE THREAD

**Issue by ascheman** [fabric8io/agent-bond#14]
We are using OpenShift 3.4, operated by AppAgile/Deutsche Telekom for a customer.

Our application is a Spring Boot application which already contains Jolokia. The base image is 

```
        from:
          kind: ImageStreamTag
          namespace: 'openshift'
          name: 'fis-java-openshift:1.0-15'
```

Jolokia is bound to a management port 8442 w/ plain http and happily responds to a local request (via Terminal session to the POD/container) using `curl localhost:8442/jolokia`:

```
{"request":{"type":"version"},"value":{"agent":"1.3.6","protocol":"7.2","config":{"agentId":"10.1.11.233-1-20b54cfe-servlet","agentType":"servlet"},"info":{}},"timestamp":1502286997,"status":200}
```

However when we try to connect via _Java Console_ from the Web UI we get an error message:

```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://10.1.11.233:8442/jolokia/?maxDepth=7&maxCollectionSize=500&ignoreErrors=true&canonicalNaming=false'
```

I have already tried several combinations of `AB_JOLOKIA_...` environment variables in the deployment configuration (cf. https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_java_s2i_for_openshift/). None of them made a difference, TLS seems to be always used for access.

Regs
  Gerd

**Comment by rhuss** [comment]
So actually the standard setup for Jolokia on OpenShift looks like this for an external access:

```
Browser ---> (openshift token auth) --> OpenShift API Server ---> TLS w. client certs ---> POD with Jolokia.
```

So Jolokia normally only accepts by default only accepts connections from the OpenShift API server, but this should be sufficient to let it connect through the OpenShift console (with included hawt.io).

And the error message above is for the connection OpenShift API server to Jolokia, not your Browser to Jolokia. Your Browser cannot reach Jolokia directly. And since the OpenShift API server will always use TLS to contact Jolokia there is no option which would change this.

When you start your application in the `oc logs <pod>`, one of the first lines gives you the startup command of the application. 

Could you please post this here to see how your concrete configuration is ? Actually you *have to* configure Jolokia for TLS (not vice versa).

**Comment by ascheman** [comment]
The application starts with the following (slightly anonymized) message:

```
Starting the application using the bundled /deployments/bin/run.sh ...
Launching application in folder: /deployments
Running  java  -Xmx1500m -Djava.security.egd=file:/dev/./urandom -XX:+ExitOnOutOfMemoryError -XX:+UseG1GC -Dspring.profiles.active=appagile  -jar /deployments/lib/xxx-SNAPSHOT.jar --spring.config.location=file:/etc/xxx-properties/
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/jboss -Duser.name=jboss
```

Thanks for the explanations. I was hoping the API server will learn from the several environment settings that it must not access Jolokia via TLS but this is obviously not the case? Will try to configure TLS for Jolokia.

**Comment by rhuss** [comment]
If you are using the FIS base images you can enable this very easily by setting the env var `AB_JOLOKIA_AUTH_OPENSHIFT=yes`. Then everything should be setup properly.

It's also, that you need the proper server cert to configure for Jolokia so that the API server will be able to connect to Jolokia. You see, the communication is heavily secured since having access to Jolokia means having control over your app.

**Comment by rhuss** [comment]
And please also check tha `AB_JOLOKIA_OFF` is not set.

**Comment by ascheman** [comment]
OK, should I drop Jolokia from Spring Boot then? I have configured it also as part of my application?

**Comment by rhuss** [comment]
Yes, that would make sense. Alternatively, you could configure you Spring-boot enabled Jolokia agent to use the proper certs.

You can see the details how this is done here: https://github.com/fabric8io/agent-bond/blob/master/fish-pepper/jolokia/fp-files/jolokia-opts#L28-L49

But the easiest way is to use the Jolokia agent from the base image.

**Comment by ascheman** [comment]
Thanks, that solved my problem!
